### ISSUE TITLE
The vise.yaml file cannot be found in Defect Calculation Parsing of the doped tutorial.

### ISSUE THREAD

**Issue by kuazhangge** [SMTG-Bham/doped#98] opened 2024-11-27 13:41 UTC
I am using the doped tutorial Defect Calculation Parsing. Regarding this tutorial, when I run the code, it gets stuck on one screen and doesn't load. Moreover, when I directly interrupt the running, it shows that the vise.yaml file cannot be found. What's going on with this?
![789 EHZGEFCWG 4ON{JISA](https://github.com/user-attachments/assets/4083a10b-9028-4a53-a987-3d15c71c2707)
![H%4 G$ DXN23N@(X{ALYI1I](https://github.com/user-attachments/assets/21a0e9f4-1f8e-46d3-b008-2eed2e130d19)

**Comment by kavanase** [comment] 2024-11-27 15:21
Hi @kuazhangge, it's likely an issue with your `vise` installation (or likely, lack thereof), but I can't tell because you don't show the actual error here.
Can you show a screenshot of the full error traceback you're getting, and also show the output of `pip show -v vise`, `pip show -v pydefect` on the terminal?

**Comment by kuazhangge** [comment] 2024-11-28 02:20
> Hi @kuazhangge, it's likely an issue with your `vise` installation (or likely, lack thereof), but I can't tell because you don't show the actual error here. Can you show a screenshot of the full error traceback you're getting, and also show the output of `pip show -v vise`, `pip show -v pydefect` on the terminal?
Thank you very much for your reply. Here are my actual errors and the output results of pip show -v vise and pip show -v pydefect.
![0))~C9BE((%G$E7~E3KL@XC](https://github.com/user-attachments/assets/71eb820c-7799-4747-aadd-18459f80ac16)
![JIHQASC(YR4YI1%E(DBNBBE](https://github.com/user-attachments/assets/32c948a2-1107-4a3d-ab05-22e214ae8a67)

![OOCH)676%LSU%2KBYYUMID9](https://github.com/user-attachments/assets/d9b38f48-16f6-427e-8d5b-6be21fc87f17)

**Comment by kavanase** [comment] 2024-11-28 02:30
Ah this makes sense. The issue is you're using Windows, and this is causing an issue with the `vise` package, which it looks like is incompatible with Windows. I would suggest installing and running python on a Linux or MacOS system if at all possible. I think some people use WSL (Windows subsystem for Linux) for this, which has solved issues for this before. I suggest trying this.

In theory, Windows OS is supported with `doped` (though not extensively tested these days), but we cannot guarantee this for the sub-packages.

**Comment by kuazhangge** [comment] 2024-11-28 02:36
> Ah this makes sense. The issue is you're using Windows, and this is causing an issue with the `vise` package, which it seems is incompatible with Windows. I would suggest installing and running python on a Linux or MacOS system if at all possible. I think some people use WSL (Windows subsystem for Linux) for this, which has solved issues for this before. I suggest trying this.
> 
> In theory, Windows OS is supported with `doped` (though not extensively tested these days), but we cannot guarantee this for the sub-packages.
Thank you very much for your help. I'll go and give it a try right now. If there are any problems that I can't solve, I'll come to seek your help again.

**Comment by kavanase** [comment] 2024-11-28 12:35
@kuazhangge I think you have tried to reply here, but you just showed my quoted text. I'm going to close this for now but feel free to comment below.

**Closed by kavanase** 2024-11-28 12:35 UTC
